version: '3'
services:
#mssql docker
  exploremostar-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - exploremostarnet

    exploremostar-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:exploreMostar=Server=exploremostar-sql,1433;Database=exploreMostarDocker;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 64741:80 
    networks:
      - exploremostarnet
    links:
      - exploremostar-sql
    depends_on:
      - exploremostar-sql
      
networks:
    exploremostarnet:
    driver: bridge  